#!/usr/bin/env python
# coding: utf-8

from __future__ import print_function
from mkcss import CSS, Color, grid
import os
c = CSS()


def read(fname):
    return open(os.path.join(os.path.dirname(__file__), fname)).read()


def randomfunction(css):
    css("font-family", "monospace")


@c.selector(".header")
def header():
    """This is a really important message
       With several lines!
       It won't show in the compact version."""
    c("font-size", "32px")
    randomfunction(c)
    c("color", "#333")


@c.selector("#mui", "#hei")
def muihei():
    randomfunction(c)
    c("box-shadow", "3px", "2px", "1px", "#333")


@c.selector("div.asd")
def asd():
    c("display", "inline-block")
    c("width", "100px")
    c("height", "100px")

    col = Color("#000000")
    for x in range(0, 11):
        @c.selector("div.asd-{0}".format(x))
        def stuff(x=x):
            newcol = col.lighten(float(x) / 10)
            c("background-color", newcol.hexrgb())
            c("color", "black" if newcol.light() else "white")


@c.selector("div.asd:after")
def asd():
    c("content", "'Mui maaila!'")

if __name__ == "__main__":
    c.header("Generated by mkcss.py")
    grid(c)
    c.make("example.css")
    c.make("example-min.css", compact=True)
